[general]
# Configuration directory, replaces variable CONFIG_DIR
config-dir = "/Users/delisa/.config/webkitten"
# Content filter used in web views
content-filter = "CONFIG_DIR/filter.json"
# Open in private mode by default
private-browsing = true
# Allow browser plugins to load, such as Flash and Silverlight
allow-plugins = false
# Allow JavaScript to run
allow-javascript = true
# Font for the command bar
bar-font = { size = 13, family = "Monaco" }
# Search engine URL used by smart-bar
search-engine-url = "https://duckduckgo.com"

[window]
# First page opened with a new window
start-page = "file://CONFIG_DIR/start_page.html"

[commands]
# Paths used to search for command files
search-paths = ["CONFIG_DIR/commands"]
# Command invoked when no commands match the first word
default = "smart-search"
# Disabled commands, skipped when searching for command matches
disabled = []
# Commands invoked when a URI is requested but before it is loaded
on-request-uri = ["enforce-https", "focus-mode"]
# Commands invoked after a document is created but before subresources are
# loaded
on-load-uri = ["user-content"]
# Commands invoked when a URI fails to load
on-fail-uri = ["fail-banner"]

# Commands invoked when command bar text changes
[commands.on-text-change]
# Run `find` when the prefix matches `/`
"/" = "find"

# Shortcuts for invoking commands
[commands.aliases]
r = "reload"
g = "go"
b = "buffer"
gh = "github"
bufn = "buffernext"
bufp = "bufferprev"
new  = "buffernew"
hl = "highlight-links"
hi = "highlight-inputs"

[commands.keybindings]
close = "cmd w"
back = "cmd ,"
forward = "cmd ."
reload = "cmd r"
buffernew = "cmd t"
"buffernew dev" = "cmd g"
windownew = "cmd n"
endfind = "cmd h"
focus-bar = "cmd shift space"
focus-webview = "cmd alt space"
toggle-bar = "cmd alt b"
highlight-links = "cmd l"
highlight-inputs = "cmd k"
buffernext = "cmd d"
bufferprev = "cmd u"
"buffer 0" = "cmd 1"
"buffer 1" = "cmd 2"
"buffer 2" = "cmd 3"
"buffer 3" = "cmd 4"
"buffer 4" = "cmd 5"
"buffer 5" = "cmd 6"
"buffer 6" = "cmd 7"
"buffer 7" = "cmd 8"

# Site-specific configuration, used as default when creating new buffers
[sites."github.com".general]
private-browsing = false

[sites."reddit.com".general]
private-browsing = false

[sites."soundcloud.com".general]
private-browsing = false

[sites."trello.com".general]
private-browsing = false

[sites."netflix.com".general]
private-browsing = false
allow-plugins = true

[user-content]
# Search paths for user scripts and stylesheets evaluated after the document is
# loaded but before subresources finish loading. Content is loaded on a
# per-site basis using page hostname as a key. Example: `example.com.js` and
# `example.com.css` will be loaded on `http://example.com/stuff`.
site-paths = ["CONFIG_DIR/user-content/sites"]
# Search paths for user scripts and stylesheets evaluated after the document is
# loaded but before subresources finish loading. Content is loaded for every
# site before the site-specific content enumerated in
# `user-content.site-paths`.
default-paths = ["CONFIG_DIR/user-content/default"]

[enforce-https]
# Skip these hosts when redirecting to HTTPS
ignored-hosts = ["fuckingblocksyntax.com","lua-users.org"]

[focus-mode]
# Hosts to allow to load while in focus mode
allowed-hosts = ["github.com","developer.apple.com",
"bugsnag.com","circleci.com", "travis-ci.org","stackoverflow.com",
"duckduckgo.com","google.com","trello.com","pivotaltracker.com",
"soundcloud.com","intercom.io"]
