brew 'caskroom/cask/brew-cask'
brew 'cask'

# Taps
tap 'caskroom/cask'
tap 'git-comment/formulae'
tap 'homebrew/bundle'
tap 'querykit/formulae'

# Desktop
cask 'airserver'
cask 'caskroom/versions/alfred2'
cask 'amethyst'
cask 'bartender'
cask 'calibre'
cask 'cleanmymac2'
cask 'disk-inventory-x'
cask 'dnscrypt'
cask 'iterm2'
cask 'karabiner'
cask 'mou'
cask 'musescore'
cask 'owncloud'
cask 'seil'
cask 'send-to-kindle'
cask 'silverlight'
cask 'sketch'
cask 'techstoreclub-simple-comic'
cask 'the-unarchiver'
cask 'time-out'
cask 'transmission'
cask 'vlc'
mas 'Deckset', id: 847496013

# Chat
cask 'telegram'
brew 'weechat', args: ['with-python', 'with-perl']

# Keyboard Config
brew 'dfu-util'

# Games
tap 'homebrew/games'
brew 'cmatrix'
brew 'homebrew/games/mednafen'
brew 'homebrew/games/nethack'
brew 'homebrew/games/nudoku'
brew 'homebrew/games/vitetris'
brew 'homebrew/games/tty-solitaire'
brew 'wine'
brew 'winetricks'
cask 'wineskin-winery'
brew 'kattrali/formulae/thyme'
brew 'itchyny/maze/maze'
cask 'adventure'
cask 'dosbox'
cask 'mari0'
cask 'openemu'

# Music
brew 'ncmpcpp', args: ['with-visualizer']
brew 'pianobar'
brew 'cmus'

# Mail
brew 'abook'
brew 'alot'
brew 'getmail'
brew 'mutt'
brew 'notmuch'

# Shells
brew 'fish'
brew 'bash'

# Development
cask 'rowanj-gitx'
cask 'alcatraz'
brew 'autoconf'
brew 'automake'
brew 'chruby'
brew 'chruby-fish'
brew 'cloc'
brew 'cmake'
brew 'doxygen'
brew 'git'
brew 'gnupg2'
brew 'go'
brew 'jsonpp'
brew 'kylef/formulae/swiftenv'
brew 'libgit2'
brew 'lua'
brew 'multirust'
brew 'openssl', args: ['universal']
brew 'progress'
brew 'python'
brew 'redis'
brew 'screenfetch'
brew 'sqlite'
brew 'the_silver_searcher'
brew 'tig'
brew 'vim'
brew 'vimpager'

# Game Dev
brew 'haxe'
cask 'aseprite'
cask 'bfxr'
cask 'magicavoxel'
cask 'sunvox'
cask 'tiled'
mas 'Pixen', id: 525180431

# Utilities
brew 'aspell'
brew 'buku'
brew 'curl'
brew 'dtrx'
brew 'fzf'
brew 'gettext'
brew 'htop'
brew 'jrnl'
brew 'jq'
brew 'khal'
brew 'ledger'
brew 'lynx'
brew 'mackup'
brew 'newsbeuter'
brew 'pass'
brew 'pkg-config'
brew 'ranger'
brew 'readline'
brew 'redshift'
brew 'tmux'
brew 'todo-txt'
brew 'trash'
brew 'tree'
brew 'urlview'
brew 'utimer'
brew 'wget'
brew 'wifi-password'
brew 'zzz'
cask 'qlmarkdown'
cask 'virtualbox'
mas 'Spectrum', id: 518156125
mas 'Sip', id: 507257563
